# Generated by Django 6.1 on 2026-08-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_curso_estudiante_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='estudiantes.curso'),
        ),
    ]
