# Generated by Django 6.1 on 2026-08-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_remove_estudiante_curso_estudiante_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='cursos',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
